---

# ---------------------------------------------------------
# General
# ---------------------------------------------------------

- name: Create directories
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ slurm_user }}"
    group: "{{ slurm_group }}"
    mode: "{{ item.mode | default('0755') }}"
  loop: "{{ slurm_dirs['slurmd'] }}"


# ---------------------------------------------------------
# slurmd
# ---------------------------------------------------------

- name: Distribute JWT token
  copy:
    src: "{{ slurm_jwt_token }}"
    dest: /etc/slurm/jwt_hs256.key
    owner: root
    group: root
    mode: "0600"
  when: slurm_jwt
  notify: Restart slurmd

- name: Configless configuration
  block:

    - name: Configure slurm to retrieve config from master
      lineinfile:
        line: SLURMD_OPTIONS='--conf-server {{ slurm_master_name }}:{{ slurm_slurmctld_port }}'
        path: /etc/{{ 'sysconfig' if ansible_os_family == 'RedHat' else 'default' }}/slurmd
        create: yes
        mode: "0644"
      notify: Restart slurmd

    - name: Create systemd custom path
      file:
        path: /etc/systemd/system/slurmd.service.d
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Change systemd configuration to skip check for slurm.conf
      copy:
        content: |
          [Unit]
          ConditionPathExists=
        dest: /etc/systemd/system/slurmd.service.d/override.conf
        owner: root
        group: root
        mode: "0644"
      notify: Restart slurmd

    - name: Reload systemd configuration
      systemd:
        daemon_reload: true

    - name: Delete obsolete configuration files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ slurm_conf_dir }}/slurm.conf"
        - "{{ slurm_conf_dir }}/cgroup.conf"
      notify: Restart slurmd

  when: slurm_configless|bool


- name: Non-configless configuration
  block:

    - name: Distribute {{ slurm_conf_dir }}/slurm.conf
      template:
        src: slurm.conf.j2
        dest: "{{ slurm_conf_dir }}/slurm.conf"
        owner: "{{ slurm_user }}"
        group: "{{ slurm_group }}"
        mode: '0644'
      notify: Restart slurmd

    - name: Distribute {{ slurm_conf_dir }}/cgroup.conf
      template:
        src: cgroup.conf.j2
        dest: "{{ slurm_conf_dir }}/cgroup.conf"
        owner: "{{ slurm_user }}"
        group: "{{ slurm_group }}"
        mode: '0600'
      notify: Restart slurmd

  when: not slurm_configless|bool

- name: Enable slurmd
  service:
    name: 'slurmd'
    enabled: yes
    state: started


# ------------------------------------------------------
# Firewall
# ------------------------------------------------------

- name: Open firewall ports
  include_role:
    name: firewall
  vars:
    firewall_ports: "{{ slurm_firewall_ports['slurmd'] }}"
  when:
    - slurm_firewall|bool
