---

- name: Create directories
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ slurm_user }}"
    group: "{{ slurm_group }}"
    mode: "{{ item.mode | default('0755') }}"
  loop: "{{ slurm_dirs['slurmd'] }}"

- name: add configless to slurm environment file
  lineinfile:
    line: SLURMD_OPTIONS='--conf-server {{ slurm_master_name }}:{{ slurm_slurmctld_port }}'
    path: /etc/sysconfig/slurmd
    create: yes
  register: _slurm_opts

- name: Distribute {{ slurm_conf_dir }}/slurm.conf
  template:
    src: slurm.conf.j2
    dest: "{{ slurm_conf_dir }}/slurm.conf"
    owner: "{{ slurm_user }}"
    group: "{{ slurm_group }}"
    mode: '0644'
  register: _slurmd

- name: Distribute {{ slurm_conf_dir }}/cgroup.conf
  template:
    src: cgroup.conf.j2
    dest: "{{ slurm_conf_dir }}/cgroup.conf"
    owner: "{{ slurm_user }}"
    group: "{{ slurm_group }}"
    mode: '0600'
  register: _cgroup

- name: Enable slurmd
  service:
    name: 'slurmd'
    enabled: yes
    state: started

- name: Restart slurmd
  service:
    name: slurmd
    state: restarted
  when: _slurmd.changed or _cgroup.changed or _slurm_opts.changed

# ------------------------------------------------------
# Firewall
# ------------------------------------------------------

- name: Open firewall ports (Debian)
  ufw:
    rule: allow
    port: "{{ (item.port|regex_replace('-',':')) if item.port is defined else omit }}"
    proto: "{{ item.proto if item.proto is defined else omit }}"
    name: "{{ item.service if item.service is defined else omit }}"
    state: enabled
  loop: "{{ slurm_firewall_ports['slurmd'] }}"
  when: ansible_os_family == 'Debian'

- name: Open firewall ports (RedHat)
  firewalld:
    port: "{{ (item.port+'/'+item.proto) if item.port is defined else omit }}"
    service: "{{ item.service if item.service is defined else omit }}"
    immediate: yes
    permanent: yes
    zone: public
    state: enabled
  loop: "{{ slurm_firewall_ports['slurmd'] }}"
  when: ansible_os_family == 'RedHat'
