---

# ---------------------------------------------------------
# General
# ---------------------------------------------------------

- name: Create directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ slurm_user }}"
    group: "{{ slurm_group }}"
    mode: "{{ item.mode | default('0755') }}"
  loop: "{{ slurm_dirs['slurmd'] }}"


# ---------------------------------------------------------
# slurmd
# ---------------------------------------------------------

- name: Distribute JWT token
  ansible.builtin.copy:
    src: "{{ slurm_jwt_token }}"
    dest: /etc/slurm/jwt_hs256.key
    owner: root
    group: root
    mode: "0600"
  when: slurm_jwt
  notify: Restart slurmd

- name: Configless configuration
  when: slurm_configless | bool
  block:

    - name: Configure slurm to retrieve config from master
      ansible.builtin.lineinfile:
        line: SLURMD_OPTIONS='--conf-server {{ slurm_master_name }}:{{ slurm_slurmctld_port }}'
        path: "{{ slurm_parm_file }}"
        create: yes
        mode: "0644"
      notify: Restart slurmd

    - name: Create systemd custom path
      ansible.builtin.file:
        path: /etc/systemd/system/slurmd.service.d
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Change systemd configuration to skip check for slurm.conf
      ansible.builtin.copy:
        content: |
          [Unit]
          ConditionPathExists=
        dest: /etc/systemd/system/slurmd.service.d/override.conf
        owner: root
        group: root
        mode: "0644"
      notify: Restart slurmd

    - name: Reload systemd configuration
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Delete obsolete configuration files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ slurm_conf_dir }}/slurm.conf"
        - "{{ slurm_conf_dir }}/cgroup.conf"
      notify: Restart slurmd


- name: Non-configless configuration
  when: not slurm_configless | bool
  block:

    - name: Disable configless
      ansible.builtin.lineinfile:
        path: "{{ slurm_parm_file }}"
        state: absent
        regexp: "--conf-server {{ slurm_master_name }}:{{ slurm_slurmctld_port }}"
        create: yes
        mode: "0644"
      notify: Restart slurmd


    - name: Distribute {{ slurm_conf_dir }}/slurm.conf  # noqa name[template]
      ansible.builtin.template:
        src: slurm.conf.j2
        dest: "{{ slurm_conf_dir }}/slurm.conf"
        owner: "{{ slurm_user }}"
        group: "{{ slurm_group }}"
        mode: '0644'
      notify: Restart slurmd
      when: slurm_conf_update | bool

    - name: Distribute {{ slurm_conf_dir }}/cgroup.conf  # noqa name[template]
      ansible.builtin.template:
        src: cgroup.conf.j2
        dest: "{{ slurm_conf_dir }}/cgroup.conf"
        owner: "{{ slurm_user }}"
        group: "{{ slurm_group }}"
        mode: '0600'
      notify: Restart slurmd

- name: Enable slurmd
  ansible.builtin.service:
    name: 'slurmd'
    enabled: yes
    state: started
  tags: molecule-idempotence-notest

# ------------------------------------------------------
# Firewall
# ------------------------------------------------------

- name: Open firewall ports for Slurm client daemon
  ansible.builtin.include_role:
    name: deitkrachten.firewall
  vars:
    firewall_ports: "{{ slurm_firewall_ports['slurmd'] }}"
  when:
    - slurm_firewall | bool
