---

- name: Load variables based on OS type
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "family-{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "family-{{ ansible_os_family }}.yml"
        - default.yml
      paths:
        - 'vars'

- name: Add slurm roles based on groups
  set_fact:
    slurm_roles: "{{ slurm_roles + [ item.role ] }}"
  loop: "{{ slurm_group2role_mapping }}"
  when: item.group in group_names

- name: Add specific repositories
  include_tasks: pre-install.yml

- name: Install slurmdbd
  block:
    - include_tasks: users.yml
    - include_tasks: install.yml
    - include_tasks: config.yml
  vars:
    slurm_role: slurmdbd
  when: "'slurmdbd' in slurm_roles"

- name: Install slurmctld
  block:
    - include_tasks: users.yml
    - include_tasks: install.yml
    - include_tasks: config.yml
  vars:
    slurm_role: slurmctld
  when: "'slurmctld' in slurm_roles"

- name: Install slurmctld
  block:
    - include_tasks: users.yml
    - include_tasks: install.yml
    - include_tasks: config.yml
  vars:
    slurm_role: slurmd
  when: "'slurmd' in slurm_roles"

