---

- name: Load variables based on OS type
  ansible.builtin.include_tasks: vars.yml

- name: Get variables that depend on the above
  ansible.builtin.include_vars: vars/override.yml

- name: Get slurm version (Suse)
  when: ansible_os_family == 'Suse'
  block:

    - name: Get slurm version (Debian)  # noqa no-changed-when
      ansible.builtin.shell: |
        set -o pipefail
        zypper info slurm 2>/dev/null | awk '/^Version/ {print $3}' | cut -f1-2 -d.
      args:
        executable: /bin/bash
      changed_when: false
      check_mode: false
      register: _slurm_version

    - name: Save slurm version
      ansible.builtin.set_fact:
        slurm_version: "{{ _slurm_version.stdout }}"

- name: Get slurm version (Debian)
  when: ansible_os_family == 'Debian'
  block:

    - name: Get slurm version (Debian)  # noqa no-changed-when
      ansible.builtin.shell: |
        set -o pipefail
        apt show slurmd 2>/dev/null | awk '/Version:/ {print $2}' | cut -f1-2 -d.
      args:
        executable: /bin/bash
      changed_when: false
      check_mode: false
      register: _slurm_version

    - name: Save slurm version
      ansible.builtin.set_fact:
        slurm_version: "{{ _slurm_version.stdout }}"

- name: Get slurm version (RedHat)
  when: ansible_os_family == 'RedHat'
  block:

    - name: Get slurm version (RedHat)  # noqa no-changed-when
      ansible.builtin.shell: |
        set -o pipefail
        dnf info slurm | awk '/^Version/ {print $NF}' | cut -f1-2 -d.
      args:
        executable: /bin/bash
      changed_when: false
      check_mode: false
      register: _slurm_version

    - name: Save slurm version
      ansible.builtin.set_fact:
        slurm_version: "{{ _slurm_version.stdout }}"

- name: Configless configuration is available from 20.02
  ansible.builtin.set_fact:
    slurm_configless: >-
      {{ true if (slurm_configless == 'auto' and slurm_version is version('20.02', '>=')) else (slurm_configless | bool) }}

- name: Add slurm roles based on groups
  ansible.builtin.set_fact:
    slurm_roles: "{{ slurm_roles + [item.role] }}"
  loop: "{{ slurm_group2role_mapping }}"
  when:
    - slurm_role is undefined
    - item.group in group_names

- name: Convert slurm_roles from string to list
  ansible.builtin.set_fact:
    slurm_roles: "{{ [slurm_role] }}"
  when: slurm_role is defined

- name: Get slurm db ip
  ansible.builtin.set_fact:
    slurm_db_ip: "{{ lookup('dig', slurm_db_host) }}"
  when: slurm_db_ip is undefined

- name: Get slurm master ip
  ansible.builtin.set_fact:
    slurm_master_ip: "{{ lookup('dig', slurm_master_name) }}"
  when: slurm_master_ip is undefined

- name: Show settings
  ansible.builtin.debug:
    msg:
      slurm:
        version: "{{ slurm_version }}"
        configless: "{{ slurm_configless }}"
        roles: "{{ slurm_roles }}"
        master_ip: "{{ slurm_master_ip }}"
        db_ip: "{{ slurm_db_ip }}"

- name: Add specific repositories
  ansible.builtin.include_tasks: pre-install.yml

- name: Install slurmdbd
  when: "'slurmdbd' in slurm_roles"
  vars:
    slurm_role: slurmdbd
  block:
    - name: Include users.yml
      ansible.builtin.include_tasks: users.yml
    - name: Include install.yml
      ansible.builtin.include_tasks: install.yml
    - name: Include config.yml
      ansible.builtin.include_tasks: config.yml

- name: Install slurmctld
  when: "'slurmctld' in slurm_roles"
  vars:
    slurm_role: slurmctld
  block:
    - name: Include users.yml
      ansible.builtin.include_tasks: users.yml
    - name: Include install.yml
      ansible.builtin.include_tasks: install.yml
    - name: Include config.yml
      ansible.builtin.include_tasks: config.yml

- name: Install slurmctld
  when: "'slurmd' in slurm_roles"
  vars:
    slurm_role: slurmd
  block:
    - name: Include users.yml
      ansible.builtin.include_tasks: users.yml
    - name: Include install.yml
      ansible.builtin.include_tasks: install.yml
    - name: Include config.yml
      ansible.builtin.include_tasks: config.yml

- name: Install slurm (client)
  when: "'client' in slurm_roles"
  vars:
    slurm_role: client
  block:
    - name: Include users.yml
      ansible.builtin.include_tasks: users.yml
    - name: Include install.yml
      ansible.builtin.include_tasks: install.yml
