---

- name: Create slurm group
  ansible.builtin.group:
    name: "{{ slurm_group }}"
    gid: "{{ slurm_gid }}"

- name: Create slurm user
  ansible.builtin.user:
    name: "{{ slurm_user }}"
    group: "{{ slurm_group }}"
    uid: "{{ slurm_uid }}"
#    home: /nonexistent
#    shell: /usr/sbin/nologin

- name: Disable password expiration
  ansible.builtin.command:
    cmd: chage -I -1 -m 0 -M -1 -E -1 {{ slurm_user }}
  changed_when: no
