---

- name: Create slurm group
  group:
    name: "{{ slurm_group }}"
    gid: "{{ slurm_gid }}"

- name: Create slurm user
  user:
    name: "{{ slurm_user }}"
    group: "{{ slurm_group }}"
    uid: "{{ slurm_uid }}"
#    home: /nonexistent
#    shell: /usr/sbin/nologin
