---

# Public - galaxy
- robertdebock.epel
- robertdebock.powertools

# Private
- name: common
  src: https://github.com/de-it-krachten/ansible-role-common.git
  version: main
  scm: git
- name: chrony
  src: https://github.com/de-it-krachten/ansible-role-chrony.git
  version: main
  scm: git
- name: firewall
  src: https://github.com/de-it-krachten/ansible-role-firewall.git
  version: main
  scm: git
- name: firewalld
  src: https://github.com/de-it-krachten/ansible-role-firewalld.git
  version: main
  scm: git
- name: iptables
  src: https://github.com/de-it-krachten/ansible-role-iptables.git
  version: main
  scm: git
- name: mariadb
  src: https://github.com/de-it-krachten/ansible-role-mariadb.git
  version: main
  scm: git
- name: munge
  src: https://github.com/de-it-krachten/ansible-role-munge.git
  version: main
  scm: git
- name: ufw
  src: https://github.com/de-it-krachten/ansible-role-ufw.git
  version: main
  scm: git
